import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Bounce, ToastContainer } from 'react-toastify';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import 'animate.css';
import dns from 'node:dns';

// Use Google's DNS servers for Node.js DNS lookups
dns.setServers(['8.8.8.8', '8.8.4.4']);

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
});

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin'],
});

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
   return (
      <html
         lang="en"
         className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
         data-theme="light"
      >
         <body className="min-h-full flex flex-col">
            <Navbar></Navbar>
            {children}
            <Footer></Footer>
            <ToastContainer
               position="top-center"
               autoClose={2000}
               hideProgressBar={false}
               newestOnTop={false}
               closeOnClick={false}
               rtl={false}
               pauseOnFocusLoss
               draggable
               pauseOnHover
               theme="light"
               transition={Bounce}
            />
         </body>
      </html>
   );
}
